export const fnKey = [
  'Backspace',
  'Tab',
  'ShiftRight',
  'ControlLeft',
  'MetaLeft',
  'AltLeft',
  'CapsLock',
  'Enter',
  'ShiftLeft',
  'Delete',
  'AltRight',
];

export const arrKey = [
  'ArrowLeft',
  'ArrowRight',
  'ArrowUp',
  'ArrowDown',
];

export const enKey = [
  [
    {
      code: 'Backquote',
      value: '`',
      shifted: '~',
      doubled: true,
    },
    {
      code: 'Digit1',
      value: '1',
      shifted: '!',
      doubled: true,
    },
    {
      code: 'Digit2',
      value: '2',
      shifted: '@',
      doubled: true,
    },
    {
      code: 'Digit3',
      value: '3',
      shifted: '#',
      doubled: true,
    },
    {
      code: 'Digit4',
      value: '4',
      shifted: '$',
      doubled: true,
    },
    {
      code: 'Digit5',
      value: '5',
      shifted: '%',
      doubled: true,
    },
    {
      code: 'Digit6',
      value: '6',
      shifted: '^',
      doubled: true,
    },
    {
      code: 'Digit7',
      value: '7',
      shifted: '&',
      doubled: true,
    },
    {
      code: 'Digit8',
      value: '8',
      shifted: '*',
      doubled: true,
    },
    {
      code: 'Digit9',
      value: '9',
      shifted: '(',
      doubled: true,
    },
    {
      code: 'Digit0',
      value: '0',
      shifted: ')',
      doubled: true,
    },
    {
      code: 'Minus',
      value: '-',
      shifted: '_',
      doubled: true,
    },
    {
      code: 'Equal',
      value: '=',
      shifted: '+',
      doubled: true,
    },
    {
      code: 'Backspace',
      value: 'delete',
      shifted: null,
      doubled: false,
    }
  ],
  [
    {
      code: 'Tab',
      value: 'tab',
      shifted: null,
      doubled: false,
    },
    {
      code: 'KeyQ',
      value: 'q',
      shifted: 'Q',
      doubled: false,
    },
    {
      code: 'KeyW',
      value: 'w',
      shifted: 'W',
      doubled: false,
    },
    {
      code: 'KeyE',
      value: 'e',
      shifted: 'E',
      doubled: false,
    },
    {
      code: 'KeyR',
      value: 'r',
      shifted: 'R',
      doubled: false,
    },
    {
      code: 'KeyT',
      value: 't',
      shifted: 'T',
      doubled: false,
    },
    {
      code: 'KeyY',
      value: 'y',
      shifted: 'Y',
      doubled: false,
    },
    {
      code: 'KeyU',
      value: 'u',
      shifted: 'U',
      doubled: false,
    },
    {
      code: 'KeyI',
      value: 'i',
      shifted: 'I',
      doubled: false,
    },
    {
      code: 'KeyO',
      value: 'o',
      shifted: 'O',
      doubled: false,
    },
    {
      code: 'KeyP',
      value: 'p',
      shifted: 'P',
      doubled: false,
    },
    {
      code: 'BracketLeft',
      value: '[',
      shifted: '{',
      doubled: true,
    },
    {
      code: 'BracketRight',
      value: ']',
      shifted: '}',
      doubled: true,
    },
    {
      code: 'Backslash',
      value: '\\',
      shifted: '|',
      doubled: true,
    },
  ],
  [
    {
      code: 'CapsLock',
      value: 'caps lock',
      shifted: null,
      doubled: false,
    },
    {
      code: 'KeyA',
      value: 'a',
      shifted: 'A',
      doubled: false,
    },
    {
      code: 'KeyS',
      value: 's',
      shifted: 'S',
      doubled: false,
    },
    {
      code: 'KeyD',
      value: 'd',
      shifted: 'D',
      doubled: false,
    },
    {
      code: 'KeyF',
      value: 'f',
      shifted: 'F',
      doubled: false,
    },
    {
      code: 'KeyG',
      value: 'g',
      shifted: 'G',
      doubled: false,
    },
    {
      code: 'KeyH',
      value: 'h',
      shifted: 'H',
      doubled: false,
    },
    {
      code: 'KeyJ',
      value: 'j',
      shifted: 'J',
      doubled: false,
    },
    {
      code: 'KeyK',
      value: 'k',
      shifted: 'K',
      doubled: false,
    },
    {
      code: 'KeyL',
      value: 'l',
      shifted: 'L',
      doubled: false,
    },
    {
      code: 'Semicolon',
      value: ';',
      shifted: ':',
      doubled: true,
    },
    {
      code: 'Quote',
      value: '\'',
      shifted: '"',
      doubled: true,
    },
    {
      code: 'Enter',
      value: 'return',
      shifted: null,
      doubled: false,
    }
  ],
  [
    {
      code: 'ShiftLeft',
      value: 'shift',
      shifted: null,
      doubled: false,
    },
    {
      code: 'KeyZ',
      value: 'z',
      shifted: 'Z',
      doubled: false,
    },
    {
      code: 'KeyX',
      value: 'x',
      shifted: 'X',
      doubled: false,
    },
    {
      code: 'KeyC',
      value: 'c',
      shifted: 'C',
      doubled: false,
    },
    {
      code: 'KeyV',
      value: 'v',
      shifted: 'V',
      doubled: false,
    },
    {
      code: 'KeyB',
      value: 'b',
      shifted: 'B',
      doubled: false,
    },
    {
      code: 'KeyN',
      value: 'n',
      shifted: 'N',
      doubled: false,
    },
    {
      code: 'KeyM',
      value: 'm',
      shifted: 'M',
      doubled: false,
    },
    {
      code: 'Comma',
      value: ',',
      shifted: '<',
      doubled: true,
    },
    {
      code: 'Period',
      value: '.',
      shifted: '>',
      doubled: true,
    },
    {
      code: 'Slash',
      value: '/',
      shifted: '?',
      doubled: true,
    },
    {
      code: 'ArrowUp',
      value: '&uarr;',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ShiftRight',
      value: 'shift',
      shifted: null,
      doubled: false,
    }
  ],
  [
    {
      code: 'ControlLeft',
      value: 'control',
      shifted: null,
      doubled: false,
    },
    {
      code: 'MetaLeft',
      value: '⌘',
      shifted: null,
      doubled: false,
    },
    {
      code: 'AltLeft',
      value: 'option',
      shifted: null,
      doubled: false,
    },
    {
      code: 'Space',
      value: ' ',
      shifted: ' ',
      doubled: false,
    },
    {
      code: 'AltRight',
      value: 'option',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ArrowLeft',
      value: '&larr;',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ArrowDown',
      value: '&darr;',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ArrowRight',
      value: '&rarr;',
      shifted: null,
      doubled: false,
    }
  ]
];

export const ruKey = [
  [
    {
      code: 'Backquote',
      value: 'ё',
      shifted: 'Ё',
      doubled: true,
    },
    {
      code: 'Digit1',
      value: '1',
      shifted: '!',
      doubled: true,
    },
    {
      code: 'Digit2',
      value: '2',
      shifted: '"',
      doubled: true,
    },
    {
      code: 'Digit3',
      value: '3',
      shifted: '№',
      doubled: true,
    },
    {
      code: 'Digit4',
      value: '4',
      shifted: ';',
      doubled: true,
    },
    {
      code: 'Digit5',
      value: '5',
      shifted: '%',
      doubled: true,
    },
    {
      code: 'Digit6',
      value: '6',
      shifted: ':',
      doubled: true,
    },
    {
      code: 'Digit7',
      value: '7',
      shifted: '?',
      doubled: true,
    },
    {
      code: 'Digit8',
      value: '8',
      shifted: '*',
      doubled: true,
    },
    {
      code: 'Digit9',
      value: '9',
      shifted: '(',
      doubled: true,
    },
    {
      code: 'Digit0',
      value: '0',
      shifted: ')',
      doubled: true,
    },
    {
      code: 'Minus',
      value: '-',
      shifted: '_',
      doubled: true,
    },
    {
      code: 'Equal',
      value: '=',
      shifted: '+',
      doubled: true,
    },
    {
      code: 'Backspace',
      value: 'delete',
      shifted: null,
      doubled: false,
    }
  ],
  [
    {
      code: 'Tab',
      value: 'tab',
      shifted: null,
      doubled: false,
    },
    {
      code: 'KeyQ',
      value: 'й',
      shifted: 'Й',
      doubled: false,
    },
    {
      code: 'KeyW',
      value: 'ц',
      shifted: 'Ц',
      doubled: false,
    },
    {
      code: 'KeyE',
      value: 'у',
      shifted: 'У',
      doubled: false,
    },
    {
      code: 'KeyR',
      value: 'к',
      shifted: 'К',
      doubled: false,
    },
    {
      code: 'KeyT',
      value: 'е',
      shifted: 'Е',
      doubled: false,
    },
    {
      code: 'KeyY',
      value: 'н',
      shifted: 'Н',
      doubled: false,
    },
    {
      code: 'KeyU',
      value: 'г',
      shifted: 'Г',
      doubled: false,
    },
    {
      code: 'KeyI',
      value: 'ш',
      shifted: 'Ш',
      doubled: false,
    },
    {
      code: 'KeyO',
      value: 'щ',
      shifted: 'Щ',
      doubled: false,
    },
    {
      code: 'KeyP',
      value: 'з',
      shifted: 'З',
      doubled: false,
    },
    {
      code: 'BracketLeft',
      value: 'х',
      shifted: 'Х',
      doubled: true,
    },
    {
      code: 'BracketRight',
      value: 'ъ',
      shifted: 'Ъ',
      doubled: true,
    },
    {
      code: 'Backslash',
      value: '\\',
      shifted: '/',
      doubled: true,
    },
  ],
  [
    {
      code: 'CapsLock',
      value: 'caps lock',
      shifted: null,
      doubled: false,
    },
    {
      code: 'KeyA',
      value: 'ф',
      shifted: 'Ф',
      doubled: false,
    },
    {
      code: 'KeyS',
      value: 'ы',
      shifted: 'Ы',
      doubled: false,
    },
    {
      code: 'KeyD',
      value: 'в',
      shifted: 'В',
      doubled: false,
    },
    {
      code: 'KeyF',
      value: 'а',
      shifted: 'А',
      doubled: false,
    },
    {
      code: 'KeyG',
      value: 'п',
      shifted: 'П',
      doubled: false,
    },
    {
      code: 'KeyH',
      value: 'р',
      shifted: 'Р',
      doubled: false,
    },
    {
      code: 'KeyJ',
      value: 'о',
      shifted: 'О',
      doubled: false,
    },
    {
      code: 'KeyK',
      value: 'л',
      shifted: 'Л',
      doubled: false,
    },
    {
      code: 'KeyL',
      value: 'д',
      shifted: 'Д',
      doubled: false,
    },
    {
      code: 'Semicolon',
      value: 'ж',
      shifted: 'Ж',
      doubled: true,
    },
    {
      code: 'Quote',
      value: 'э',
      shifted: 'Э',
      doubled: true,
    },
    {
      code: 'Enter',
      value: 'return',
      shifted: null,
      doubled: false,
    }
  ],
  [
    {
      code: 'ShiftLeft',
      value: 'shift',
      shifted: null,
      doubled: false,
    },
    {
      code: 'KeyZ',
      value: 'я',
      shifted: 'Я',
      doubled: false,
    },
    {
      code: 'KeyX',
      value: 'ч',
      shifted: 'Ч',
      doubled: false,
    },
    {
      code: 'KeyC',
      value: 'с',
      shifted: 'С',
      doubled: false,
    },
    {
      code: 'KeyV',
      value: 'м',
      shifted: 'М',
      doubled: false,
    },
    {
      code: 'KeyB',
      value: 'и',
      shifted: 'И',
      doubled: false,
    },
    {
      code: 'KeyN',
      value: 'т',
      shifted: 'Т',
      doubled: false,
    },
    {
      code: 'KeyM',
      value: 'ь',
      shifted: 'Ь',
      doubled: false,
    },
    {
      code: 'Comma',
      value: 'б',
      shifted: 'Б',
      doubled: true,
    },
    {
      code: 'Period',
      value: 'ю',
      shifted: 'Ю',
      doubled: true,
    },
    {
      code: 'Slash',
      value: '.',
      shifted: ',',
      doubled: true,
    },
    {
      code: 'ArrowUp',
      value: '&uarr;',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ShiftRight',
      value: 'shift',
      shifted: null,
      doubled: false,
    }
  ],
  [
    {
      code: 'ControlLeft',
      value: 'control',
      shifted: null,
      doubled: false,
    },
    {
      code: 'MetaLeft',
      value: '⌘',
      shifted: null,
      doubled: false,
    },
    {
      code: 'AltLeft',
      value: 'option',
      shifted: null,
      doubled: false,
    },
    {
      code: 'Space',
      value: ' ',
      shifted: ' ',
      doubled: false,
    },
    {
      code: 'AltRight',
      value: 'option',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ArrowLeft',
      value: '&larr;',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ArrowDown',
      value: '&darr;',
      shifted: null,
      doubled: false,
    },
    {
      code: 'ArrowRight',
      value: '&rarr;',
      shifted: null,
      doubled: false,
    }
  ]
];
